[project]
name = "convert-to-pdf-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.109.0",
    "python-dotenv==1.0.0",
    "python-multipart==0.0.9",
    "uvicorn[standard]==0.27.0",
]
